name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js 20.11.1
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.1'

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        with:
          REMOTE_HOST: "52.28.7.64"
          REMOTE_USER: "ubuntu"
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "."  # Path to the source files in your repository
          TARGET: "sudo /var/www/html/screepho"  # Destination directory on EC2 instance
